name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      databend:
        image: docker.io/datafuselabs/databend
        env:
          QUERY_DEFAULT_USER: databend
          QUERY_DEFAULT_PASSWORD: databend
          MINIO_ENABLED: true
        ports:
          - 8000:8000
          - 9000:9000
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: default
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Service Running
        run: |
          sleep 60
          curl -v http://localhost:8000/v1/health

      - name: Test
        env:
          TEST_DATABEND_DSN: "http://databend:databend@localhost:8000"
        run: |
          go test -v -p 1 -cover ./...